# vim: sts=2 sw=2 et:

os: linux
dist: trusty
group: stable

language: cpp
services:
- docker

matrix:
  include:
    - env: "IMAGE=archlinux-build TARGETS=codecov"
    - env: "IMAGE=debian-build:latest TARGETS=test"
    - env: "IMAGE=debian-build:testing TARGETS=test"
    - env: "IMAGE=ubuntu-build:latest TARGETS=test"
    - env: "IMAGE=ubuntu-build:devel TARGETS=test"
    - env: "IMAGE=centos-build:latest TARGETS=test"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# really?
# watch https://docs.travis-ci.com/user/gui-and-headless-browsers/ to
# see if a less fragile version comes up (with services maybe)

script:
    - bash scripts/docker/exec.bash
