FROM debian:latest

RUN apt update
RUN apt -y install --no-install-recommends build-essential libglew-dev libglm-dev libsdl2-dev libsdl2-image-dev libsdl2-net-dev libsdl2-ttf-dev libopenal-dev libalut-dev zlib1g-dev libcppunit-dev
